# Generated by Django 5.2.1 on 2025-05-26 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='id_proofs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
